---
version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - ginkgolinter
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - revive
    # - staticcheck
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: add-constant
          arguments:
            - allowInts: 0,1,2,3
              allowStrs: '""'
              ignoreFuncs: assert\.Len,require\.Len
              maxLitCount: "5"
        - name: line-length-limit
          arguments:
            - 120
          severity: warning
          exclude:
            - ""
        - name: comment-spacings
          disabled: true
        - name: indent-error-flow
          disabled: true
        - name: use-errors-new
          disabled: true
        - name: bare-return
        - name: cognitive-complexity
          disabled: true
        - name: context-as-argument
        - name: cyclomatic
          disabled: true
        - name: dot-imports
          arguments:
            - allowedPackages:
                - github.com/onsi/ginkgo/v2
                - github.com/onsi/gomega
        - name: early-return
        - name: empty-block
        - name: empty-lines
        - name: exported
          disabled: true
        - name: function-length
        - name: if-return
        - name: import-alias-naming
        - name: import-shadowing
        - name: increment-decrement
        - name: max-control-nesting
        - name: max-public-structs
          arguments:
            - 14
        - name: redefines-builtin-id
        - name: receiver-naming
        - name: redundant-import-alias
        - name: struct-tag
        - name: superfluous-else
        - name: unchecked-type-assertion
        - name: unexported-naming
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
        path: internal/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
