run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: 'api/*'
      linters:
        - lll
    - path: 'internal/*'
      linters:
        - dupl
        - lll
linters:
  disable-all: true
  enable:
    #- dupl
    #- errcheck
    # WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
    # ERRO [linters_context] exportloopref: This linter is fully inactivated: it will not produce any reports.
    #- exportloopref
    - ginkgolinter
    #- goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    #- lll
    - misspell
    #- nakedret
    #- prealloc
    - revive
    #- staticcheck
    - typecheck
    #- unconvert
    #- unparam
    - unused

linters-settings:
  revive:
    rules:
      - name: comment-spacings
      - name: add-constant
        arguments:
          - allowStrs: '""'
            allowInts: '0,1,2,3'
            ignoreFuncs: "assert\\.Len"
            maxLitCount: '5'
      - name: line-length-limit
        severity: warning
        disabled: true
        exclude: ['']
        arguments: [120]
      - name: add-constant
        disabled: true
      - name: comment-spacings
        disabled: true
