run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  # restore some of the defaults
  # (fill in the rest as needed)
  exclude-rules:
    - path: 'internal/*'
      linters:
        - dupl
linters:
  disable-all: true
  enable:
    #- dupl
    #- errcheck
    # WARN The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
    # ERRO [linters_context] exportloopref: This linter is fully inactivated: it will not produce any reports.
    #- exportloopref
    - ginkgolinter
    #- goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    # - lll
    - misspell
    #- nakedret
    #- prealloc
    - revive
    #- staticcheck
    - typecheck
    #- unconvert
    #- unparam
    - unused

linters-settings:
  revive:
    rules:
      - name: comment-spacings
      - name: add-constant
        arguments:
          - allowStrs: '""'
            allowInts: '0,1,2,3'
            ignoreFuncs: "assert\\.Len"
            maxLitCount: '5'
      - name: line-length-limit
        severity: warning
        exclude: ['']
        arguments: [120]

      # devotional-phoenix: Fixing is seperate PR's:
      - name: add-constant
        disabled: true
      - name: comment-spacings
        disabled: true
      - name: indent-error-flow
        disabled: true
      - name: unused-receiver
        disabled: true
      - name: add-constant
        disabled: true
      - name: use-errors-new
        disabled: true
      - name: unused-parameter
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: var-declaration
        disabled: true
      - name: var-naming
        disabled: true

      # axiomatic-fixed-chimpanzee: Fixing is seperate PR's:
      - name: bare-return
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: context-as-argument
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: dot-imports
        disabled: true
      - name: early-return
        disabled: true
      - name: empty-block
        disabled: true
      - name: empty-lines
        disabled: true
      - name: exported
        disabled: true
      - name: function-length
        disabled: true
      - name: if-return
        disabled: true

      # hikarukin: Fixing is seperate PR's:
      - name: import-alias-naming
        disabled: true
      - name: import-shadowing
        disabled: true
      - name: increment-decrement
        disabled: true
      - name: max-control-nesting
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: redefines-builtin-id
        disabled: true
      - name: receiver-naming
        disabled: true
      - name: redundant-import-alias
        disabled: true
      - name: struct-tag
      - name: superfluous-else
        disabled: true
      - name: unchecked-type-assertion
        disabled: true
      - name: unexported-naming
        disabled: true
