# (mandatory)
# Path to coverage profile file (output of `go test -coverprofile` command).
#
# For cases where there are many coverage profiles, such as when running
# unit tests and integration tests separately, you can combine all those
# profiles into one. In this case, the profile should have a comma-separated list
# of profile files, e.g., 'cover_unit.out,cover_integration.out'.
profile: cover.out

# (optional; but recommended to set)
# When specified reported file paths will not contain local prefix in the output.
local-prefix: 'github.com/belastingdienst/opr-paas'

# Holds coverage thresholds percentages, values should be in range [0-100].
threshold:
  # (optional; default 0)
  # Minimum coverage percentage required for individual files.
  file: 70

  # (optional; default 0)
  # Minimum coverage percentage required for each package.
  package: 80

  # (optional; default 0)
  # Minimum overall project coverage percentage required.
  total: 55

# Holds regexp rules which will override thresholds for matched files or packages
# using their paths.
#
# First rule from this list that matches file or package is going to apply
# new threshold to it. If project has multiple rules that match same path,
# override rules should be listed in order from specific to more general rules.
override:
  # Increase coverage threshold to 100% for `foo` package
  # (default is 80, as configured above in this example).
  #- path: ^pkg/lib/foo$
  #  threshold: 100
  - path: ^internal/controller$
    threshold: 30
  - path: ^api/v1alpha1$
    threshold: 68
  - path: ^internal/crypt$
    threshold: 65
  - path: ^internal/config$
    threshold: 23

  - path: api/v1alpha1/paasconfig_types.go
    threshold: 10
  - path: api/v1alpha2/paas_types.go
    threshold: 50
  - path: internal/config/watcher.go
    threshold: 0
  - path: internal/controller/argo_app.go
    threshold: 69
  - path: internal/controller/argo_projects.go
    threshold: 68
  - path: internal/controller/argocd.go
    threshold: 35
  - path: internal/controller/capabilities.go
    threshold: 58
  - path: internal/controller/cluster_quotas.go
    threshold: 43
  - path: internal/controller/cluster_wide_quota.go
    threshold: 13
  - path: internal/controller/clusterrolebindings.go
    threshold: 0
  - path: internal/controller/groups.go
    threshold: 40
  - path: internal/controller/ldap_groups.go
    threshold: 36
  - path: internal/controller/namespaces.go
    threshold: 33
  - path: internal/controller/paas_controller.go
    threshold: 28
  - path: internal/controller/paasconfig_controller.go
    threshold: 0
  - path: internal/controller/paasnamespaces.go
    threshold: 59
  - path: internal/controller/paasns_controller.go
    threshold: 5
  - path: internal/controller/rolebindings_controller.go
    threshold: 10
  - path: internal/controller/secret_controller.go
    threshold: 68
  - path: internal/crypt/main.go
    threshold: 12

# Holds regexp rules which will exclude matched files or packages
# from coverage statistics.
exclude:
  # Exclude files or packages matching their paths
  paths:
    - cmd
    - e2e
    - internal/stubs
    - zz_generated.*\.go$

# File name of go-test-coverage breakdown file, which can be used to
# analyze coverage difference.
breakdown-file-name: ''

diff:
  # File name of go-test-coverage breakdown file which will be used to
  # report coverage difference.
  base-breakdown-file-name: ''
