apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: ghcr.io/belastingdienst/opr-paas
  newName: ghcr.io/belastingdienst/opr-paas
  newTag: feature/install_yaml_release

resources:
- config
- crds
- manager
- rbac
