# permissions for end users to view paasns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: paasns-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: opr-paas
    app.kubernetes.io/part-of: opr-paas
    app.kubernetes.io/managed-by: kustomize
  name: paasns-viewer-role
rules:
- apiGroups:
  - cpet.belastingdienst.nl
  resources:
  - paasns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cpet.belastingdienst.nl
  resources:
  - paasns/status
  verbs:
  - get
