---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cpet.belastingdienst.nl
  resources:
  - paas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cpet.belastingdienst.nl
  resources:
  - paas/finalizers
  verbs:
  - update
- apiGroups:
  - cpet.belastingdienst.nl
  resources:
  - paas/status
  verbs:
  - get
  - patch
  - update
