apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: paas-controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: opr-paas
    app.kubernetes.io/part-of: opr-paas
    app.kubernetes.io/managed-by: kustomize
  name: paas-system