#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GENERATED_DIR="${ROOT_DIR}/test/e2e/.generated/crypt"
MANIFEST_DIR="${ROOT_DIR}/test/e2e/manifests/cryptkeys"
PRIVATE_KEY="${GENERATED_DIR}/privateKey0"
PUBLIC_KEY="${GENERATED_DIR}/publicKey0"
SECRET_MANIFEST="${MANIFEST_DIR}/generated-paas-crypt-keys.yaml"

mkdir -p "${GENERATED_DIR}" "${MANIFEST_DIR}"

openssl genrsa 4096 > "${PRIVATE_KEY}" 2>/dev/null
openssl rsa -pubout -in "${PRIVATE_KEY}" -out "${PUBLIC_KEY}" 2>/dev/null

PRIVATE_KEY_B64="$(base64 < "${PRIVATE_KEY}" | tr -d '\n')"

cat > "${SECRET_MANIFEST}" <<EOF
# Generated by hack/generate-e2e-cryptkeys.sh. Do not commit.
apiVersion: v1
kind: Secret
metadata:
  name: example-keys
  namespace: paas-system
type: Opaque
data:
  privateKey0: ${PRIVATE_KEY_B64}
EOF
