apiVersion: my.domain/v1alpha1
kind: Paas
metadata:
  labels:
    app.kubernetes.io/name: paas
    app.kubernetes.io/instance: paas-sample
    app.kubernetes.io/part-of: opr-paas
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: opr-paas
  name: paas-sample
spec:
  # TODO(user): Add fields here
