---
apiVersion: cpet.belastingdienst.nl/v1alpha1
kind: Paas
metadata:
  labels:
    app.kubernetes.io/name: paas
    app.kubernetes.io/instance: paas-sample
    app.kubernetes.io/part-of: opr-paas
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: opr-paas
  name: paa-paa
spec:
  oplosGroep: acme
  groups:
    paashaas:
      users:
      - aap
      - paa
  quota:
    limits.cpu: "13"
    limits.memory: 42Gi
    requests.cpu: "10"
    requests.memory: 32Gi
    requests.storage: 1024Gi
    thin.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
  capabilities:
    argocd:
      enabled: true
      quota:
        limits.cpu: "1"
        limits.memory: 4Gi
        requests.cpu: "800m"
        requests.memory: 3Gi
        requests.storage: 10Gi
        thin.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
      gitUrl: https://
    ci:
      quota:
        limits.cpu: "1"
        limits.memory: 4Gi
        requests.cpu: "800m"
        requests.memory: 3Gi
        requests.storage: 10Gi
        thin.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    sso:
      quota:
        limits.cpu: "1"
        limits.memory: 4Gi
        requests.cpu: "800m"
        requests.memory: 3Gi
        requests.storage: 10Gi
        thin.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    grafana:
      quota:
        limits.cpu: "1"
        limits.memory: 4Gi
        requests.cpu: "800m"
        requests.memory: 3Gi
        requests.storage: 10Gi
        thin.storageclass.storage.k8s.io/persistentvolumeclaims: "0"

