apiVersion: cpet.belastingdienst.nl/v1alpha1
kind: PaasNS
metadata:
  labels:
    app.kubernetes.io/name: paasns
    app.kubernetes.io/instance: paasns-sample
    app.kubernetes.io/part-of: opr-paas
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: opr-paas
  # Results in sam-ple-featuire-test1
  name: feature-test1
  namespace: sam-ple-argocd
spec:
  #paas should be discoverable from namespace and existing paas objects
  #paas: sam-ple
  groups:
    - group1
    - group2
  sshSecrets:
    'ssh://git@vcs/proj/repo/': >-
      2wkeKe==
  separateQuota: false
