---
apiVersion: cpet.belastingdienst.nl/v1alpha1
kind: Paas
metadata:
  labels:
    app.kubernetes.io/name: paas
    app.kubernetes.io/instance: paas-sample
    app.kubernetes.io/part-of: opr-paas
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: opr-paas
  name: aap-aap
spec:
  requestor: acme
  groups:
    appa:
      query: CN=appa,OU=paas,OU=caas,OU=corp,DC=prod,DC=acme,DC=org
      users:
      - aap
      - paa
  quota:
    limits.cpu: "13"
    limits.memory: 42Gi
    requests.cpu: "10"
    requests.memory: 32Gi
    requests.storage: 1024Gi
    thin.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
  capabilities:
    argocd:
      enabled: true
      quota:
        limits.cpu: "2"
        limits.memory: 5Gi
        requests.cpu: "1Gi"
        requests.memory: 4Gi
        requests.storage: 20Gi
        thin.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
      gitUrl: https://
    tekton:
      quota:
        limits.cpu: "2"
        limits.memory: 5Gi
        requests.cpu: "1Gi"
        requests.memory: 4Gi
        requests.storage: 20Gi
        thin.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    sso:
      quota:
        limits.cpu: "2"
        limits.memory: 5Gi
        requests.cpu: "1Gi"
        requests.memory: 4Gi
        requests.storage: 20Gi
        thin.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
    grafana:
      quota:
        limits.cpu: "2"
        limits.memory: 5Gi
        requests.cpu: "1Gi"
        requests.memory: 4Gi
        requests.storage: 20Gi
        thin.storageclass.storage.k8s.io/persistentvolumeclaims: "0"
