apiVersion: cpet.belastingdienst.nl/v1alpha2
kind: PaasConfig
metadata:
  name: paas-config
spec:
  capabilities:
    argocd:
      applicationset: argoas
      default_permissions:
        argo-service-applicationset-controller:
          - monitoring-edit
        argo-service-argocd-application-controller:
          - monitoring-edit
      extra_permissions:
        argo-service-argocd-application-controller:
          - admin
      quotas:
        clusterwide: false
        defaults:
          limits.cpu: '5'
          limits.memory: 4Gi
          requests.cpu: '1'
          requests.memory: 1Gi
          requests.storage: '0'
          thin.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
        ratio: 0
    grafana:
      applicationset: grafanaas
      quotas:
        clusterwide: false
        defaults:
          limits.cpu: '2'
          limits.memory: 2Gi
          requests.cpu: 500m
          requests.memory: 512Mi
          requests.storage: 2Gi
          thin.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
        ratio: 0
    sso:
      applicationset: ssoas
      quotas:
        clusterwide: false
        defaults:
          limits.cpu: '1'
          limits.memory: 512Mi
          requests.cpu: 100m
          requests.memory: 128Mi
          requests.storage: '0'
          thin.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
        ratio: 0
    tekton:
      applicationset: tektonas
      default_permissions:
        pipeline:
          - view
          - alert-routing-edit
      extra_permissions:
        pipeline:
          - admin
      quotas:
        clusterwide: true
        defaults:
          limits.cpu: '5'
          limits.memory: 8Gi
          requests.cpu: '1'
          requests.memory: 2Gi
          requests.storage: 100Gi
          thin.storageclass.storage.k8s.io/persistentvolumeclaims: '0'
        max:
          requests.cpu: '10'
          requests.memory: 10Gi
        min:
          limits.cpu: '5'
          limits.memory: 4Gi
        ratio: 0.1
  clusterwide_argocd_namespace: asns
  components_debug:
    paas_controller: false
    secret_controller: false
  debug: false
  decryptKeySecret:
    name: example-keys
    namespace: paas-system
  feature_flags:
    group_user_management: allow
  managed_by_label: argocd.argoproj.io/manby
  managed_by_suffix: argocd
  quota_label: q.lbl
  requestor_label: o.lbl
  rolemappings:
    default:
      - admin
    viewer:
      - view
  validations:
    paas:
      name: '^[a-z0-9-]*$'
      groupName: '^[a-z0-9-]*$'
      namespaceName: '^[a-z0-9-]*$'
      requestor: '^[a-z0-9-]*$'
      allowedQuotas: '^(limits.memory|requests.cpu|requests.memory|requests.storage)$'
    paasConfig:
      capabilityName: '^[a-z0-9-]*$'
    paasNs:
      name: '^[a-z0-9-]*$'
