---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cpet-belastingdienst-nl-v1alpha1-paas
  failurePolicy: Fail
  name: vpaas-v1alpha1.kb.io
  rules:
  - apiGroups:
    - cpet.belastingdienst.nl
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - paas
  sideEffects: None
