name: Build and add install.yaml to release
on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  sbom:
    name: Generate and upload install.yaml
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.0.0

      - name: Install kustomize
        run: make kustomize

      - name: Generate install.yaml
        run: make build-installer
        env:
          IMAGE_TAG: ${{ github.ref_name }}

      - name: Add install.yaml to release
        uses: softprops/action-gh-release@62c96d0c4e8a889135c1f3a25910db8dbe0e85f7 # v2.3.4
        with:
          files: manifests/install.yaml
