name: Build and add install.yaml to release
on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  sbom:
    name: Generate and upload install.yaml
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@8410ad0602e1e429cee44a835ae9f77f654a6694 # v4.0.0

      - name: Install kustomize
        run: make kustomize

      - name: Generate install.yaml
        run: make build-installer
        env:
          IMAGE_TAG: ${{ github.ref_name }}

      - name: Add install.yaml to release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          files: manifests/install.yaml
