name: Build and add install.yaml to release
on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  sbom:
    name: Generate and upload install.yaml
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install kustomize
        run: make kustomize

      - name: Generate install.yaml
        run: make build-installer
        env:
          IMAGE_TAG: ${{ github.ref_name }}

      - name: Add install.yaml to release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          files: manifests/install.yaml
