name: Build and publish documentation
on:
  workflow_dispatch:
  release:
    types:
      - published
env:
  PYTHON_VERSION: 3.x
  # Golang version to use across CI steps
  GOLANG_VERSION: '1.25'
  
permissions:
  contents: write

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    
    services:
      kroki:
        image: yuzutech/kroki@sha256:4cfb9d48a1d9e18c346d505fd85c9ad16121d1691602b0e580db904b00c04320
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl -f http://localhost:8000/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        
      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages --depth=1

      - name: Set up Go for generating API doc
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ env.GOLANG_VERSION }}
      
      - name: Generate API document
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          go install github.com/elastic/crd-ref-docs@6d9cbb2645274941d10941cc988a49e873562fba
          crd-ref-docs --config=./crd-ref-docs-config.yml --source-path=./api --renderer=markdown --output-path=./docs/development-guide/00_api.md
        working-directory: ${{ github.workspace }}

      - name: Set up Python runtime
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: |
            requirements.txt

      - name: Set up build cache
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          key: mkdocs-material-${{ hashfiles('.cache/**') }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install Python dependencies
        run: |
          pip install --no-cache-dir mkdocs-material \
                                     mkdocs-literate-nav \
                                     mkdocs-redirects \
                                     mkdocs-material[recommended] \
                                     mkdocs-material[imaging] \
                                     mkdocs-kroki-plugin \
                                     mike

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Extract short tag
        id: extract_short_tag
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name || github.ref_name }}
        run: |
          SHORT_TAG="$(echo "$RELEASE_TAG" | sed 's/\([0-9]*\.[0-9]*\).*/\1\.x/')"
          if [[ -z "$SHORT_TAG" ]]; then
            echo "ERROR: Could not extract short tag from RELEASE_TAG='$RELEASE_TAG'"
            exit 1
          fi
          echo "SHORT_TAG=$SHORT_TAG" >> "$GITHUB_OUTPUT"

      - name: Deploy with mike 🚀
        # note that "mike set-default latest" was run manually in initial docs setup
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          STEPS_EXTRACT_SHORT_TAG_OUTPUTS_SHORT_TAG: ${{ steps.extract_short_tag.outputs.SHORT_TAG }}
          KROKI_SERVER_URL: http://kroki:8000
        run: |
          SHORT_TAG=${STEPS_EXTRACT_SHORT_TAG_OUTPUTS_SHORT_TAG}
          mike deploy --update-aliases --push --branch=gh-pages "$SHORT_TAG" latest
          mike --version
          
      - name: Save build cache
        uses: actions/cache/save@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          key: mkdocs-material-${{ hashfiles('.cache/**') }}
          path: .cache
