name: Release workflow for building images and adding to ghcr.io
on:
  release:
    types:
      - published

jobs:
  image:
    name: Push Docker image to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: homedash-meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name=ghcr.io/belastingdienst/opr-paas,enable=true
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: 'linux/amd64,linux/arm64'
          tags: ${{ steps.homedash-meta.outputs.tags }}
          labels: ${{ steps.homedash-meta.outputs.labels }}
