name: Release workflow for building images and adding to ghcr.io
on:
  release:
    types:
      - published

jobs:
  image:
    name: Push Docker image to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: 'Build'
        run: |
          docker build -t opr-paas .
      - name: 'tag and push to ghcr.io'
        run: |
          for TAG in latest ${{ github.ref_name }}; do
            docker tag opr-paas ghcr.io/belastingdienst/opr-paas:${TAG}
            docker push ghcr.io/belastingdienst/opr-paas:${TAG}
          done
