name: publiccode.yml validation

on:
  pull_request:
    paths:
      - publiccode.yml
  push:
    branches: [main] # Usually best to restrict push triggers to your default branch
    paths:
      - publiccode.yml

# Prevent redundant runs on the same PR/branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  publiccode_yml_validation:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Validation should be very fast
    permissions:
      contents: read # Explicitly allow reading the repository content
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 1 # Only need the latest commit for validation

      - name: Validate publiccode.yml
        uses: italia/publiccode-parser-action@0deab88c3f094aa12c5826e52ac2c4f176446821 # v1
        with:
          publiccode: "publiccode.yml"