name: publiccode.yml validation

on:
  pull_request:
    paths:
      - publiccode.yml
  push:
    branches: [main] # Usually best to restrict push triggers to your default branch
    paths:
      - publiccode.yml

# Prevent redundant runs on the same PR/branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  publiccode_yml_validation:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Validation should be very fast
    permissions:
      contents: read # Explicitly allow reading the repository content
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 1 # Only need the latest commit for validation

      - name: Validate publiccode.yml
        uses: italia/publiccode-parser-action@56e1200cba853b1efa73ee871600284d0705ab4d # v1
        with:
          publiccode: "publiccode.yml"