apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: paas-leader-election-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: opr-paas
    app.kubernetes.io/part-of: opr-paas
    app.kubernetes.io/managed-by: kustomize
  name: paas-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: paas-leader-election-role
subjects:
- kind: ServiceAccount
  name: paas-controller-manager
  namespace: paas-system
